services:
    database:
        image: mysql:8.4
        platform: linux/x86_64
        command: '--mysql-native-password=ON --max_allowed_packet=32505856'
        volumes:
            - "./.mysql-data:/var/lib/mysql"
            - "./db:/docker-entrypoint-initdb.d"
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
            - MYSQL_USER=${WORDPRESS_DB_USER}
            - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
        expose:
            - 3306
        ports:
            - "3306:3306"
        networks:
            - openprofile_network

    wordpress:
        image: wordpress:latest
        volumes:
            - "./app:/var/www/html"
            - "../wordpress-fact-pod:/var/www/html/wp-content/plugins/wordpress-fact-pod"
        ports:
            - 80:80
        restart: always
        environment:
            - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
            - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
            - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
            - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
            - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
        networks:
            - openprofile_network

networks:
    openprofile_network: {}

